### ISSUE TITLE
serial communication failure

### ISSUE THREAD

**Issue by luschardt** [merose/ROSRomeoNode#1] opened 2020-07-09 19:44 UTC
after loading the code to the arduino I ran the following commands
$ roscore
$ rosrun rosserial_python serial_node.py / dev / ttyACM0

and I received the following errors:

[ERROR] [1594323447.825093]: Parameter ~control_rate does not exist
[WARN] [1594323448.817141]: Failed to get param: timeout expired
[ERROR] [1594323448.822213]: Parameter ticks_meter does not exist
[WARN] [1594323449.816532]: Failed to get param: timeout expired
[ERROR] [1594323449.821665]: Parameter ~vtarget_timeout does not exist
[WARN] [1594323450.820065]: Failed to get param: timeout expired
[WARN] [1594323496.950566]: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

**Comment by merose** [comment] 2020-07-09 23:08
Be aware that this code is for a Pololu A-Star module, an Arduino-like microcontroller, but not an Arduino. Also, I've given up on using rosserial_arduino because of its high memory usage; it's very easy to get heap/stack collision on the microcontroller and have things not work, or some topics work and not others (in strange ways). I wouldn't recommend using this code unless you want to make modifications for it to work with your microcontroller, and then only if you're using a controller with much more memory than a 2k byte Arduino.

The parameters it's complaining about are supposed to be optional, as indicated in the Arduino code, but it's possible that the version of rosserial_arduino that you're using is requiring them to be present. Have you tried it while providing those parameters on the `rosrun` command line?

**Comment by luschardt** [comment] 2020-07-10 00:02
I am a beginner in the world of ROS and I had doubts when it came to running rosrun with the parameters. I adapted the code to run on an arduino uno, I removed the parameters and apparently it is working, now I would like to integrate now your diff_drive repository could you help me with some tips?

**Comment by merose** [comment] 2020-07-10 01:12
Sure. I have run them together previously. Since you need to run multiple nodes and hook them together properly, with various parameters, it's vastly easier if you learn how to use launch files and start things using roslaunch. You might look at some tutorials to help in this regard. I'll close this issue, for now, and you can open a new issue if you run into problems or have questions. And if the issue is with a diff_drive node – though I understand since you're new to ROS it may be difficult to determine where a problem is – it would be better to create an issue there.

**Closed as completed by merose** 2020-07-10 01:12 UTC
